"""allow bool on permission

Revision ID: a7f4c3398956
Revises: 4c8471c51c70
Create Date: 2024-05-19 17:56:34.875300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a7f4c3398956"
down_revision: Union[str, None] = "4c8471c51c70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "permission",
        sa.Column("allow", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('permission', 'allow', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("permission", "allow")
    # ### end Alembic commands ###
